---
- name: Import OpenTelemetry Operator installation tasks
  ansible.builtin.import_tasks:
    file: install_opentelemetry_operator.yaml

- name: Import OpenTelemetry Collectors installation tasks
  ansible.builtin.import_tasks:
    file: install_opentelemetry_collectors.yaml
