---
- name: Import Clickhouse Operator installation tasks
  ansible.builtin.import_tasks:
    file: install_clickhouse_operator.yaml

- name: Import Clickhouse Instance installation tasks
  ansible.builtin.import_tasks:
    file: install_clickhouse_instances.yaml
