---
- name: Retrieve secret containing Clickhouse default user credentials
  kubernetes.core.k8s_info:
    kind: Secret
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    name: user-default-credentials
    namespace: "{{ tools_managers.clickhouse_operator.instances.kubernetes.namespace }}"
  register: tools_clickhouse_default_user_secret

- name: Verify that object exists
  ansible.builtin.assert:
    that:
      - tools_clickhouse_default_user_secret.api_found
      - tools_clickhouse_default_user_secret.resources | ansible.builtin.length == 1
    fail_msg: Unable to find default user secret for main Clickhouse cluster. Please verify that Clickhouse is installed.
    success_msg: Found default user secret information for main Clickhouse cluster.

- name: Extract Clickhouse user credentials
  ansible.builtin.set_fact:
    tools_clickhouse_username: |-
      {{
        tools_clickhouse_default_user_secret.resources[0].data.user |
        ansible.builtin.b64decode
      }}
    tools_clickhouse_password: |- # pragma: allowlist secret
      {{
        tools_clickhouse_default_user_secret.resources[0].data.password |
        ansible.builtin.b64decode
      }}
