---
- name: Retrieve host address from Gateway
  when:
    - tools_cluster.platform == "kubernetes"
  block:
    - name: Retrieve HTTPRoute for Clickhouse
      kubernetes.core.k8s_info:
        api_version: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        name: "{{ tools_managers.clickhouse_operator.instances.names.main }}"
        namespace: "{{ tools_managers.clickhouse_operator.instances.kubernetes.namespace }}"
      register: tools_clickhouse_http_route

    - name: Validate that Clickhouse HTTPRoute exists
      ansible.builtin.assert:
        that:
          - tools_clickhouse_http_route.api_found
          - tools_clickhouse_http_route.resources | ansible.builtin.length == 1
        fail_msg: Clickhouse route not found. Please verify that Clickhouse was successfully installed.
        success_msg: Clickhouse route found.

    - name: Create Clickhouse external endpoint
      ansible.builtin.set_fact:
        tools_clickhouse_endpoint:
          host: |-
            {{
              (
                tools_service_provider_address |
                ansible.builtin.default(tools_gateway_http_address) |
                ansible.builtin.default("")
              ) +
              tools_clickhouse_http_route.resources[0].spec.rules[0].matches[0].path.value
            }}
          paths:
            - /play

- name: Retrieve host address from Routes
  when:
    - tools_cluster.platform == "openshift"
  block:
    - name: Retrieve Route for Clickhouse
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        name: "{{ tools_managers.clickhouse_operator.instances.names.main }}"
        namespace: "{{ tools_managers.clickhouse_operator.instances.kubernetes.namespace }}"
      register: tools_clickhouse_route

    - name: Validate that Clickhouse Route exists
      ansible.builtin.assert:
        that:
          - tools_clickhouse_route.api_found
          - tools_clickhouse_route.resources | ansible.builtin.length == 1
        fail_msg: Clickhouse route not found. Please verify that Clickhouse was successfully installed.
        success_msg: Clickhouse route found.

    - name: Create Clickhouse external endpoint
      ansible.builtin.set_fact:
        tools_clickhouse_endpoint:
          host: "http://{{ tools_clickhouse_route.resources[0].status.ingress[0].host }}"
          paths:
            - /play
      when:
        - tools_clickhouse_route.resources[0].status.ingress is defined
        - tools_clickhouse_route.resources[0].status.ingress | ansible.builtin.length > 0
