---
- name: Retrieve host address from Gateway
  when:
    - tools_cluster.platform == "kubernetes"
  block:
    - name: Retrieve HTTPRoute for Jaeger
      kubernetes.core.k8s_info:
        api_version: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        name: "{{ tools_managers.opentelemetry_operator.instances.names.jaeger }}"
        namespace: "{{ tools_managers.opentelemetry_operator.instances.kubernetes.namespace }}"
      register: tools_jaeger_http_route

    - name: Validate that Jaeger HTTPRoute exists
      ansible.builtin.assert:
        that:
          - tools_jaeger_http_route.api_found
          - tools_jaeger_http_route.resources | ansible.builtin.length == 1
        fail_msg: Jaeger route not found. Please verify that Jaeger was successfully installed.
        success_msg: Jaeger route found.

    - name: Create Jaeger external endpoint
      ansible.builtin.set_fact:
        tools_jaeger_endpoint:
          host: |-
            {{
              (
                tools_service_provider_address |
                ansible.builtin.default(tools_gateway_http_address) |
                ansible.builtin.default("")
              ) +
              tools_jaeger_http_route.resources[0].spec.rules[0].matches[0].path.value
            }}
          paths:
            - /

- name: Retrieve host address from Routes
  when:
    - tools_cluster.platform == "openshift"
  block:
    - name: Retrieve Route for Jaeger
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        name: "{{ tools_managers.opentelemetry_operator.instances.names.jaeger }}"
        namespace: "{{ tools_managers.opentelemetry_operator.instances.kubernetes.namespace }}"
      register: tools_jaeger_route

    - name: Validate that Jaeger Route exists
      ansible.builtin.assert:
        that:
          - tools_jaeger_route.api_found
          - tools_jaeger_route.resources | ansible.builtin.length == 1
        fail_msg: Jaeger route not found. Please verify that Jaeger was successfully installed.
        success_msg: Jaeger route found.

    - name: Create Jaeger external endpoint
      ansible.builtin.set_fact:
        tools_jaeger_endpoint:
          host: |-
            {{
              [
                "http://",
                tools_jaeger_route.resources[0].status.ingress[0].host,
                tools_jaeger_route.resources[0].spec.path
              ] |
              ansible.builtin.join
            }}
          paths:
            - /
      when:
        - tools_jaeger_route.resources[0].status.ingress is defined
        - tools_jaeger_route.resources[0].status.ingress | ansible.builtin.length > 0
