---
- name: Retrieve host address from Gateway
  when:
    - tools_cluster.platform == "kubernetes"
  block:
    - name: Retrieve HTTPRoute for Prometheus
      kubernetes.core.k8s_info:
        api_version: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        name: "{{ tools_managers.prometheus.helm.release.name }}"
        namespace: "{{ tools_managers.prometheus.kubernetes.namespace }}"
      register: tools_prometheus_http_route

    - name: Validate that Prometheus HTTPRoute exists
      ansible.builtin.assert:
        that:
          - tools_prometheus_http_route.api_found
          - tools_prometheus_http_route.resources | ansible.builtin.length == 1
        fail_msg: Prometheus route not found. Please verify that Prometheus was successfully installed.
        success_msg: Prometheus route found.

    - name: Create Prometheus external endpoint
      ansible.builtin.set_fact:
        tools_prometheus_endpoint:
          host: |-
            {{
              (
                tools_service_provider_address |
                ansible.builtin.default(tools_gateway_http_address) |
                ansible.builtin.default("")
              ) +
              tools_prometheus_http_route.resources[0].spec.rules[0].matches[0].path.value
            }}
          paths:
            - /alerts
            - /query
      when:
        - tools_prometheus_http_route.api_found
        - tools_prometheus_http_route.resources | ansible.builtin.length == 1

- name: Retrieve host address from Routes
  when:
    - tools_cluster.platform == "openshift"
  block:
    - name: Retrieve Route for Prometheus
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        name: prometheus-k8s
        namespace: openshift-monitoring
      register: tools_prometheus_route

    - name: Validate that Prometheus Route exists
      ansible.builtin.assert:
        that:
          - tools_prometheus_route.api_found
          - tools_prometheus_route.resources | ansible.builtin.length == 1
        fail_msg: Prometheus route not found. Please verify that Prometheus was successfully installed.
        success_msg: Prometheus route found.

    - name: Create Prometheus external endpoint
      ansible.builtin.set_fact:
        tools_prometheus_endpoint:
          host: "http://{{ tools_prometheus_route.resources[0].status.ingress[0].host }}"
          paths:
            - /alerts
            - /query
      when:
        - tools_prometheus_route.resources[0].status.ingress is defined
        - tools_prometheus_route.resources[0].status.ingress | ansible.builtin.length > 0
