---
- name: Retrieve host address from Gateway
  when:
    - tools_cluster.platform == "kubernetes"
  block:
    - name: Retrieve HTTPRoute for OpenCost
      kubernetes.core.k8s_info:
        api_version: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        name: "{{ tools_managers.opencost.helm.release.name }}"
        namespace: "{{ tools_managers.opencost.kubernetes.namespace }}"
      register: tools_opencost_http_route

    - name: Validate that OpenCost Route exists
      ansible.builtin.assert:
        that:
          - tools_opencost_http_route.api_found
          - tools_opencost_http_route.resources | ansible.builtin.length == 1
        fail_msg: OpenCost route not found. Please verify that OpenCost was successfully installed.
        success_msg: OpenCost route found.

    - name: Create OpenCost external endpoint
      ansible.builtin.set_fact:
        tools_opencost_endpoint:
          host: |-
            {{
              (
                tools_service_provider_address |
                ansible.builtin.default(tools_gateway_http_address) |
                ansible.builtin.default("")
              ) +
              tools_opencost_http_route.spec.rules[0].matches[0].path.value
            }}
          paths:
            - /

- name: Retrieve host address from Routes
  when:
    - tools_cluster.platform == "openshift"
  block:
    - name: Retrieve Route for OpenCost
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        name: "{{ tools_managers.opencost.helm.release.name }}"
        namespace: "{{ tools_managers.opencost.kubernetes.namespace }}"
      register: tools_opencost_route

    - name: Validate that OpenCost Route exists
      ansible.builtin.assert:
        that:
          - tools_opencost_route.api_found
          - tools_opencost_route.resources | ansible.builtin.length == 1
        fail_msg: OpenCost route not found. Please verify that OpenCost was successfully installed.
        success_msg: OpenCost route found.

    - name: Create OpenCost external endpoint
      ansible.builtin.set_fact:
        tools_opencost_endpoint:
          host: "http://{{ tools_opencost_route.resources[0].status.ingress[0].host }}"
          paths:
            - /
      when:
        - tools_opencost_route.resources[0].status.ingress is defined
        - tools_opencost_route.resources[0].status.ingress | ansible.builtin.length > 0
