---
- name: Import Clickhouse Instance uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_clickhouse_instances.yaml

- name: Import Clickhouse Operator uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_clickhouse_operator.yaml
