---
- name: Import OpenTelemetry Collectors uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_opentelemetry_collectors.yaml

- name: Import OpenTelemetry Operator uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_opentelemetry_operator.yaml
