version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    groups:
      actions-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directories:
      - "scenarios/ciso/"
    groups:
      docker-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: daily

  - package-ecosystem: "docker"
    directories:
      - "scenarios/sre/roles/applications/files/bookinfo/loadgenerator.yaml"
      - "scenarios/sre/roles/faults/files/**/deployment*.yaml"
      - "scenarios/sre/roles/recorders/files/**/**/"
      - "scenarios/sre/roles/tools/files/opensearch/"
      - "scenarios/sre/tools/kubernetes-topology-monitor/"
      - "scenarios/sre/tools/kubernetes-topology-monitor/charts/kubernetes-topology-monitor/templates/"
      - "scenarios/sre/tools/hello-bench/"
    groups:
      docker-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: daily

  - package-ecosystem: "gomod"
    directories:
      - "scenarios/sre/dev/local_cluster/"
    groups:
      go-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directories:
      - "scenarios/"
      - "scenarios/sre/"
      - "scenarios/sre/roles/recorders/files/**/**/scripts/"
      - "scenarios/sre/tools/kubernetes-topology-monitor/"
    groups:
      pip-production-dependencies:
        dependency-type: "production"
      pip-development-dependencies:
        dependency-type: "development"
    schedule:
      interval: "daily"
