repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - args:
          - --allow-multiple-documents
        id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
  - hooks:
      - id: ansible-lint
        stages:
          - pre-commit
    repo: https://github.com/ansible/ansible-lint
    rev: v26.2.0
  - hooks:
      - args:
          - --baseline
          - .secrets.baseline
        id: detect-secrets
    repo: https://github.com/IBM/detect-secrets
    rev: 0.13.1+ibm.64.dss
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
