---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-51
spec:
  alerts:
    - labels: {}
      name: HighRequestLatency
  entities:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: otel-demo
  solutions:
    - - steps:
          - command: kubectl -n otel-demo edit deployment workload-scanner
            text: Manually edit the manifest and lower the request rate.
      - steps:
          - command: kubectl -n otel-demo delete deployment workload-scanner
            text: Delete the injected load generator deployment.
