---
- name: Run agent revoke access tasks
  hosts:
    - environment
  tasks:
    - name: Import agent role to revoke access
      ansible.builtin.import_role:
        name: agent
      vars:
        agent_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"
