---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      faults_cluster:
        options:
          kubeconfig:
            required: true
            type: str
        required: false
        type: dict
      faults_injection_tasks:
        default: []
        elements: dict
        options:
          args:
            required: true
            type: dict
          id:
            choices:
              - cordoned-kubernetes-worker-node
              - disabled-istio-ambient-mode-kubernetes-namespace
              - failing-name-resolution-kubernetes-workload-dns-policy
              - hanging-kubernetes-workload-init-container
              - ingress-port-blocking-network-policy
              - insufficient-kubernetes-resource-quota
              - insufficient-kubernetes-workload-container-resources
              - invalid-kubernetes-workload-container-command
              - kubernetes-api-server-request-surge
              - misconfigured-kubernetes-horizontal-pod-autoscaler
              - misconfigured-kubernetes-workload-container-readiness-probe
              - modified-kubernetes-workload-container-environment-variable
              - modified-target-port-kubernetes-service
              - nonexistent-kubernetes-workload-container-image
              - nonexistent-kubernetes-workload-node
              - nonexistent-kubernetes-workload-persistent-volume-claim
              - opentelemetry-demo-feature-flag
              - malformed-configmap-service-crash
              - priority-kubernetes-workload-priority-preemption
              - scheduled-chaos-mesh-experiment
              - strict-mutual-tls-istio-service-mesh-enforcement
              - traffic-denying-istio-gateway-authorization-policy
              - unassigned-kubernetes-workload-container-resource-limits
              - unschedulable-kubernetes-workload-pod-anti-affinity-rule
              - unsupported-architecture-kubernetes-workload-container-image
              - valkey-workload-changed-password
              - valkey-workload-out-of-memory
              - scaled-to-zero-kubernetes-workload
              - istio-service-mesh-routing-corruption
            required: true
            type: str
        required: false
        type: list
