---
- name: Import Book Info installation tasks
  ansible.builtin.import_tasks:
    file: install_book_info.yaml
  when:
    - applications_configuration.bookInfo.enabled | ansible.builtin.default(false)

- name: Import OpenTelemetry Demo installation tasks
  ansible.builtin.import_tasks:
    file: install_opentelemetry_demo.yaml
  when:
    - applications_configuration.opentelemetryDemo.enabled | ansible.builtin.default(false)
