---
- name: Import Istio's BookInfo uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_book_info.yaml

- name: Import OpenTelemetry Demo uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_otel_demo.yaml
