---
- name: Uninstall OpenTelemetry Demo (Astronomy Shop)
  kubernetes.core.helm:
    kubeconfig: "{{ applications_cluster.kubeconfig }}"
    release_name: "{{ applications_helm_releases.otel_demo.name }}"
    release_namespace: "{{ applications_helm_releases.otel_demo.namespace }}"
    release_state: absent
    wait: true

- name: Delete the release namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ applications_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ applications_helm_releases.otel_demo.namespace }}"
    state: absent
    wait: true
