---
- name: Set scenario variables
  ansible.builtin.set_fact:
    scenarios_scenario: |-
      {{
        lookup(
          'ansible.builtin.file',
          [directory_path, 'scenario.yaml'] | ansible.builtin.path_join
        ) |
        ansible.builtin.from_yaml
      }}
    scenarios_ground_truth: |-
      {{
        lookup(
          'ansible.builtin.file',
          [directory_path, 'groundtruth.yaml'] | ansible.builtin.path_join
        ) |
        ansible.builtin.from_yaml
      }}
  vars:
    directory_path: |-
      {{
        [
          role_path,
          "files",
          [
            'scenario',
            scenarios_identifier
          ] | ansible.builtin.join('_')
        ] |
        ansible.builtin.path_join
      }}
