---
- name: Set scenario variables
  ansible.builtin.set_fact:
    scenarios_scenario: "{{ lookup('ansible.builtin.file', [directory_path, 'scenario.yaml'] | path_join) | from_yaml }}"
    scenarios_ground_truth: "{{ lookup('ansible.builtin.file', [directory_path, 'groundtruth.yaml'] | path_join) | from_yaml }}"
  vars:
    directory_path: |-
      {{
        [
          role_path,
          "files",
          [
            'scenario',
            scenarios_identifier
          ] | join('_')
        ] |
        path_join
      }}
