---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      applications_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            required: true
            type: str
      applications_configuration:
        required: false
        type: dict
