---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      applications_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            required: true
            type: str
      applications_configuration:
        required: true
        type: dict
        options:
          book_info:
            required: false
            type: dict
            options:
              enabled:
                default: true
                required: false
                type: bool
              options:
                required: false
                type: dict
                options:
                  autoscaling:
                    required: false
                    type: dict
                    options:
                      enabled:
                        default: false
                        required: false
                        type: bool
          otel_demo:
            required: false
            type: dict
            options:
              enabled:
                default: true
                required: false
                type: bool
              options:
                required: false
                type: dict
                options:
                  autoscaling:
                    required: false
                    type: dict
                    options:
                      enabled:
                        default: false
                        required: false
                        type: bool
                  load_generation:
                    required: false
                    type: dict
                    options:
                      browser_traffic:
                        default: false
                        required: false
                        type: bool
                      users:
                        default: 50
                        required: false
                        type: int
                      users_spawn_rate:
                        default: 5
                        required: false
                        type: int
