---
- name: Create schedule
  kubernetes.core.k8s:
    kubeconfig: "{{ injections_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ injections_args.kubernetesObject.apiVersion }}"
      kind: "{{ injections_args.kubernetesObject.kind }}"
      metadata:
        name: "{{ injections_args.kubernetesObject.metadata.name }}"
        namespace: "{{ injections_args.kubernetesObject.metadata.namespace }}"
      spec: |-
        {{
          injections_args.scheduleSpec |
          combine(
            {
              "concurrencyPolicy": "Forbid",
              "historyLimit": 1,
              "schedule": "* * * * *"
            }
          )
        }}
    state: present

- name: Retrieve newly created schedule
  kubernetes.core.k8s_info:
    apiVersion: "{{ injections_args.kubernetesObject.apiVersion }}"
    kind: "{{ injections_args.kubernetesObject.kind }}"
    kubeconfig: "{{ injections_cluster.kubeconfig }}"
    name: "{{ injections_args.kubernetesObject.metadata.name }}"
    namespace: "{{ injections_args.kubernetesObject.metadata.namespace }}"
  register: injections_schedule
  until:
    - injections_schedule.resources | ansible.builtin.length == 1
    - injections_schedule.resources[0].status.active is defined
    - injections_schedule.resources[0].status.active | ansible.builtin.length == 1
  delay: 10
  retries: 12

- name: Wait for experiment to be injected
  kubernetes.core.k8s_info:
    api_version: "{{ experiment.apiVersion }}"
    kind: "{{ experiment.kind }}"
    kubeconfig: "{{ injections_cluster.kubeconfig }}"
    name: "{{ experiment.name }}"
    namespace: "{{ experiment.namespace }}"
    wait: true
    wait_condition:
      status: "True"
      type: AllInjected
  loop: "{{ injections_schedule.resources[0].status.active }}"
  loop_control:
    label: "{{ experiment.kind | lower }}/{{ experiment.name }}"
    loop_var: experiment
