---
- name: Retrieve configmap
  kubernetes.core.k8s_info:
    kubeconfig: "{{ injections_cluster.kubeconfig }}"
    api_version: "{{ injections_args.kubernetesObject.apiVersion }}"
    kind: "{{ injections_args.kubernetesObject.kind }}"
    name: "{{ injections_args.kubernetesObject.metadata.name }}"
    namespace: "{{ injections_args.kubernetesObject.metadata.namespace }}"
  register: injections_configmap

- name: Validate that valid configmap exists
  ansible.builtin.assert:
    that:
      - injections_configmap is defined
      - injections_configmap.resources | ansible.builtin.length == 1
    fail_msg: Unable to find configmap. Please verify that the configmap exists.
    success_msg: Found configmap.

- name: Validate that flagd data exists
  ansible.builtin.assert:
    that:
      - injections_configmap.resources[0].data["demo.flagd.json"] is defined
    fail_msg: Unable to find data. Please verify that the flagd data exists.
    success_msg: Found data.

- name: Update configmap data
  kubernetes.core.k8s:
    kubeconfig: "{{ injections_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ injections_configmap.resources[0].apiVersion }}"
      kind: "{{ injections_configmap.resources[0].kind }}"
      metadata:
        name: "{{ injections_configmap.resources[0].metadata.name }}"
        namespace: "{{ injections_configmap.resources[0].metadata.namespace }}"
      data:
        "demo.flagd.json": |-
          {{
            injections_configmap.resources[0].data["demo.flagd.json"] |
            combine(
              {
                "flags": {
                  injections_args.flag.name: {
                    "defaultVariant": injections_args.flag.state
                  }
                }
              },
              recursive=true
            ) |
            to_json
          }}
    state: patched
