---
- name: Import Chaos Mesh schedule removal tasks
  ansible.builin.import_tasks:
    file: remove_chaos_mesh_schedules.yaml

- name: Import Kubernetes cluster-scoped objects removal tasks
  ansible.builtin.import_tasks:
    file: remove_cluster_scoped_objects.yaml
