---
applications_managers:
  book_info:
    git:
      # renovate: datasource=github-tags depName=istio/istio
      repository: https://github.com/istio/istio.git
      tag: 1.29.0
    kubernetes:
      namespace: book-info
  opentelemetry_demo:
    helm:
      chart:
        # renovate: datasource=docker depName=ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-demo
        reference: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-demo
        version: 0.40.4
      release:
        name: otel-demo
    kubernetes:
      namespace: otel-demo
