---
- name: Import access granting tasks
  ansible.builtin.import_tasks:
    file: grant.yaml
  tags:
    - grant_access

- name: Import access revoking tasks
  ansible.builtin.import_tasks:
    file: revoke.yaml
  tags:
    - revoke_access
