---
- name: Retrieve all agent access related RoleBindings
  kubernetes.core.k8s_info:
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    label_selectors:
      - app.kubernetes.io/component = agent-access-provider
      - app.kubernetes.io/managed-by = ITBench
  register: agent_access_role_bindings

- name: Delete all agent access related RoleBindings
  kubernetes.core.k8s:
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ role_binding.apiVersion }}"
      kind: "{{ role_binding.kind }}"
      metadata:
        name: "{{ role_binding.metadata.name }}"
        namespace: "{{ role_binding.metadata.namespace }}"
    state: absent
    wait: true
  loop: "{{ agent_access_role_bindings.resources }}"
  loop_control:
    label: rolebinding/{{ role_binding.metadata.name }}
    loop_var: role_binding

- name: Retrieve all agent access related Role
  kubernetes.core.k8s_info:
    api_version: rbac.authorization.k8s.io/v1
    kind: Role
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    label_selectors:
      - app.kubernetes.io/component = agent-access-provider
      - app.kubernetes.io/managed-by = ITBench
  register: agent_access_roles

- name: Delete all agent access related Role
  kubernetes.core.k8s:
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ role.apiVersion }}"
      kind: "{{ role.kind }}"
      metadata:
        name: "{{ role.metadata.name }}"
        namespace: "{{ role.metadata.namespace }}"
    state: absent
    wait: true
  loop: "{{ agent_access_roles.resources }}"
  loop_control:
    label: role/{{ role.metadata.name }}
    loop_var: role

- name: Delete Namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ agent_managers.access_provider.kubernetes.namespace }}"
    state: absent
    wait: true
