---
- name: Delete all RoleBindings for agent access
  kubernetes.core.k8s:
    api_version: rbac.authorization.k8s.io/v1
    delete_all: true
    kind: RoleBinding
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    label_selectors:
      - app.kubernetes.io/component = agent-access-provider
      - app.kubernetes.io/managed-by = ITBench
    state: absent
    wait: true

- name: Delete all Roles for agent access
  kubernetes.core.k8s:
    api_version: rbac.authorization.k8s.io/v1
    delete_all: true
    kind: Role
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    label_selectors:
      - app.kubernetes.io/component = agent-access-provider
      - app.kubernetes.io/managed-by = ITBench
    state: absent
    wait: true

- name: Delete Namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ agent_managers.access_provider.kubernetes.namespace }}"
    state: absent
    wait: true
