---
- name: Import applications docs generation tasks
  ansible.builtin.import_tasks:
    file: generate_applications_docs.yaml

- name: Import faults docs generation tasks
  ansible.builtin.import_tasks:
    file: generate_faults_docs.yaml

- name: Import waiters docs generation tasks
  ansible.builtin.import_tasks:
    file: generate_waiters_docs.yaml

- name: Import scenarios docs generation tasks
  ansible.builtin.import_tasks:
    file: generate_scenarios_docs.yaml
