---
- name: Create identifiers for applications
  ansible.builtin.set_fact:
    documentation_applications_library: |
      {{
        (
          documentation_applications_library |
          ansible.builtin.default([])
        ) +
        [
          (
            application |
            ansible.builtin.combine(
              {
                "id": (
                  application.name |
                  ansible.builtin.lower |
                  ansible.builtin.replace(" ", "-")
                )
              }
            )
          )
        ]
      }}
  loop: |-
    {{
      lookup("ansible.builtin.file", "files/library/applications/index.json") |
      ansible.builtin.from_json
    }}
  loop_control:
    label: application/{{ application.name }}
    loop_var: application

- name: Generate applications library index
  ansible.builtin.copy:
    content: |
      {{
        documentation_applications_library |
        ansible.builtin.sort(attribute="name") |
        ansible.builtin.to_nice_json
      }}
    dest: "{{ [role_path, 'files', 'library', 'applications', 'index.json'] | ansible.builtin.path_join }}"
    mode: "0644"

- name: Generate applications README
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/readmes/applications.j2') }}"
    dest: "{{ playbook_dir }}/../docs/applications.md"
    mode: "0644"
  vars:
    documentation_contents: |-
      {{
        lookup("ansible.builtin.file", "files/library/applications/index.json") |
        ansible.builtin.from_json
      }}
