---
- name: Import docs generation tasks
  ansible.builtin.import_tasks:
    file: generate.yaml
  tags:
    - generate_docs

- name: Import docs validation tasks
  ansible.builtin.import_tasks:
    file: validate.yaml
  tags:
    - validate_docs
