---
- name: Import applications docs validation tasks
  ansible.builtin.import_tasks:
    file: validate_applications_docs.yaml

- name: Import faults docs validation tasks
  ansible.builtin.import_tasks:
    file: validate_faults_docs.yaml

- name: Import waiters docs generation tasks
  ansible.builtin.import_tasks:
    file: validate_waiters_docs.yaml

- name: Import scenarios docs validation tasks
  ansible.builtin.import_tasks:
    file: validate_scenarios_docs.yaml
