---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-53
spec:
  alerts:
    - labels: {}
      name: KubePodNotReady
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: reviews-v3
        namespace: book-info
  solutions:
    - - steps:
          - command: kubectl -n book-info rollout undo deployment/reviews-v3
            text: Revert the last change done to the manifest.
      - steps:
          - command: kubectl -n book-info edit persistentvolumeclaim reviews-v3
            text: Manually edit the manifest and replace the `storageClassName` with the correct value.
      - steps:
          - command: kubectl -n book-info edit deployment reviews-v3
            text: Manually edit the manifest and replace the volume claim with an existing persistent volume claim.
