---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-37
spec:
  applications:
    opentelemetryDemo:
      enabled: true
      options:
        autoscaling:
          kubernetes: true
  faults: []
  tools:
    chaosEngineering:
      chaosMesh:
        enabled: false
    costMonitoring:
      opencost:
        enabled: true
    observability:
      topology:
        enabled: true
      traces:
        enabled: true
