---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-37
spec:
  applications:
    opentelemetryDemo:
      enabled: true
      options:
        autoscaling:
          kubernetes:
            hpa: true
  faults: []
  tools:
    finops:
      enabled: true
