---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-48
spec:
  alerts:
    - labels: {}
      name: NoRequestsReceived
  entities:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: book-info
  solutions:
    - - steps:
          - command: kubectl -n book-info edit namespace book-info-deny
            text: Manually edit the manifest and replace the invalid label with the correct value.
