---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-48
spec:
  applications:
    bookInfo:
      enabled: true
  faults:
    - injections:
        - args:
            kubernetesObject:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: book-info
          id: disabled-istio-ambient-mode-kubernetes-namespace
  tools:
    sre:
      enabled: true
