---
scaffolding_faults_index_path: "{{ playbook_dir }}/../roles/documentation/files/library/faults/index.json"
scaffolding_faults_schema_path: "{{ playbook_dir }}/../roles/documentation/files/library/faults/schema.json"
scaffolding_faults_tasks_dir: "{{ playbook_dir }}/../roles/faults/tasks"
scaffolding_scenarios_files_dir: "{{ playbook_dir }}/../roles/scenarios/files"
scaffolding_scenarios_index_path: "{{ playbook_dir }}/../roles/documentation/files/library/scenarios/index.json"
scaffolding_scenarios_schema_path: "{{ playbook_dir }}/../roles/documentation/files/library/scenarios/schema.json"
