---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      injections_cluster:
        options:
          kubeconfig:
            required: true
            type: str
        required: false
        type: dict
      injections_tasks:
        elements: dict
        options:
          args:
            required: true
            type: dict
          id:
            choices:
              - cordoned-kubernetes-worker-node
              - disabled-istio-ambient-mode-kubernetes-namespace
              - failing-name-resolution-kubernetes-workload-dns-policy
              - hanging-kubernetes-workload-init-container
              - ingress-port-blocking-network-policy
              - insufficent-kubernetes-resource-quota
              - insufficent-kubernetes-workload-container-resources
              - invalid-kubernetes-workload-container-command
              - misconfigured-kubernetes-horizontal-pod-autoscaler
              - misconfigured-kuberntes-workload-container-readiness-probe
              - modified-kubernetes-workload-container-environment-variable
              - modified-target-port-kubernetes-service
              - nonexistent-kubernetes-workload-container-image
              - nonexistent-kubernetes-workload-node
              - opentelemetry-demo-feature-flag
              - priority-kubernetes-workload-priority-preemption
              - scheduled-chaos-mesh-experiment
              - strict-mutual-tls-istio-service-mesh-enforcement
              - traffic-denying-istio-gateway-authorization-policy
              - unassigned-kubernetes-workload-container-resource-limits
              - unschedueable-kuberntes-workload-pod-anti-affinity-rule
              - unsupported-architecture-kubernetes-workload-container-image
              - valkey-workload-changed-password
              - valkey-workload-out-of-memory
            required: true
            type: str
        required: true
        type: list
