---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-47
spec:
  alerts:
    - labels: {}
      name: NoRequestsReceived
  entities:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: bookinfo-gateway
        namespace: book-info
    - apiVersion: security.istio.io/v1
      kind: AuthorizationPolicy
      metadata:
        name: bookinfo-gateway-deny
        namespace: book-info
  solutions:
    - - steps:
          - command: kubectl -n book-info edit authorizationpolicy bookinfo-gateway-deny
            text: Manually edit the manifest and replace the invalid rule with the correct value.
      - steps:
          - command: kubectl -n book-info delete authorizationpolicy bookinfo-gateway-deny
            text: Delete the faulty authorization policy.
