apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-image-pull-secret
spec:
  background: true
  rules:
  - name: sync-regcred-secret
    match:
      any:
      - resources:
          kinds:
          - Namespace
          operations:
          - CREATE
          - UPDATE
    exclude:
      any:
      - resources:
          namespaces:
          - kyverno
    generate:
      synchronize: true
      apiVersion: v1
      kind: Secret
      name: regcred
      namespace: "{{request.object.metadata.name}}"
      clone:
        namespace: default
        name: regcred
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecret-to-serviceaccounts
spec:
  rules:
  - name: add-registry-secret-to-sa
    match:
      any:
      - resources:
          kinds:
          - ServiceAccount
    exclude:
      any:
      - resources:
          namespaces:
          - kube-public
          - kube-node-lease
          - kyverno
    mutate:
      patchStrategicMerge:
        imagePullSecrets:
        - name: regcred
