---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      agent_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
      agent_access_request:
        type: dict
        required: false
        options:
          namespaces:
            elements: str
            required: true
            type: list
      agent_storage:
        required: false
        type: dict
        options:
          local:
            required: false
            type: dict
            options:
              directory:
                required: true
                type: str
          s3:
            required: false
            type: dict
            options:
              bucket:
                required: true
                type: str
              directory:
                required: true
                type: str
              endpoint:
                required: true
                type: str
