---
argument_specs:
  generate_files:
    author:
      - Gerard Vanloo
    options:
      scenarios_files_generator:
        options:
          options:
            options:
              overwrite:
                default: false
                required: false
                type: bool
            required: false
            type: dict
        required: false
        type: dict
  main:
    author:
      - Gerard Vanloo
    options:
      scenarios_identifier:
        choices:
          - 1
          - 3
          - 16
          - 18
          - 20
          - 23
          - 26
          - 27
          - 30
          - 31
          - 33
          - 34
          - 37
          - 38
          - 39
          - 40
          - 41
          - 42
          - 43
          - 44
          - 45
          - 46
          - 47
          - 48
          - 49
          - 50
          - 51
          - 53
          - 54
          - 55
          - 102
          - 105
        required: true
        type: int
