---
- name: Retrieve the traces recorder pod name
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    namespace: "{{ recorders_namespace.name }}"
    label_selectors:
      - app.kubernetes.io/name = jaeger-traces-recorder
      - app.kubernetes.io/part-of = it-bench
  register: recorders_jaeger_pods_info

# NOTE: The shell command is used over the Ansible module because the k8s_cp module
#       can fail with internal errors even when the pod is healthy.

- name: Ensure local directory exists
  ansible.builtin.file:
    path: /tmp/traces
    state: directory
    mode: "0755"
  when:
    - recorders_jaeger_pods_info.resources | length == 1

- name: Copy records directory from pod
  ansible.builtin.shell: |
    set -o pipefail
    kubectl exec \
      --kubeconfig={{ recorders_cluster.kubeconfig | ansible.builtin.expanduser }} \
      -n {{ recorders_jaeger_pods_info.resources[0].metadata.namespace }} \
      {{ recorders_jaeger_pods_info.resources[0].metadata.name }} \
      -c recorder \
      -- tar cf - -C /opt/app-root/src/records --exclude='lost+found' . | \
    tar xf - -C /tmp/traces/
  args:
    executable: /bin/bash
  register: recorders_jaeger_copy_output
  changed_when: recorders_jaeger_copy_output.rc == 0
  when:
    - recorders_jaeger_pods_info.resources | length == 1

- name: Uninstall Jaeger Traces Recorder
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: StatefulSet
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    name: jaeger-traces-recorder
    namespace: "{{ recorders_namespace.name }}"
    state: absent
    wait: true

- name: Delete ConfigMap with Python script
  kubernetes.core.k8s:
    api_version: v1
    delete_all: true
    kind: ConfigMap
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    namespace: "{{ recorders_namespace.name }}"
    label_selectors:
      - app.kubernetes.io/name = jaeger-traces-recorder
      - app.kubernetes.io/part-of = it-bench
    state: absent
    wait: true

- name: Find all exported JSON files
  ansible.builtin.find:
    path: /tmp/traces
    patterns:
      - "*.json"
  register: recorders_jaeger_files

- name: Ensure trace_information directory exists on local
  ansible.builtin.file:
    path: "{{ recorders_storage.local.directory }}/trace_information"
    state: directory
    mode: "0755"
  when:
    - recorders_storage.local is defined

- name: Copy exported data into local directory
  ansible.builtin.copy:
    dest: "{{ recorders_storage.local.directory }}/trace_information/{{ file.path | basename }}"
    mode: "0644"
    src: "{{ file.path }}"
  loop: "{{ recorders_jaeger_files.files }}"
  loop_control:
    label: file/{{ file.path | basename }}
    loop_var: file
  when:
    - recorders_storage.local is defined
    - recorders_jaeger_files is defined

- name: Upload exported data to S3 bucket
  amazon.aws.s3_object:
    endpoint_url: "{{ recorders_storage.s3.endpoint }}"
    bucket: "{{ recorders_storage.s3.bucket }}"
    object: "{{ recorders_storage.s3.directory }}/trace_information/{{ file.path | basename }}"
    src: "{{ file.path }}"
    mode: put
  loop: "{{ recorders_jaeger_files.files }}"
  loop_control:
    label: file/{{ file.path | basename }}
    loop_var: file
  when:
    - recorders_storage.s3 is defined
    - recorders_jaeger_files is defined
