apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-38
spec:
  applications:
    opentelemetryDemo:
      enabled: true
      options:
        autoscaling:
          kubernetes:
            hpa: true
  faults:
  - injections:
    - args:
        kubernetesObject:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: fraud-detection
            namespace: otel-demo
      id: misconfigured-kubernetes-horizontal-pod-autoscaler
    - args:
        kubernetesObject:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: frontend
            namespace: otel-demo
      id: misconfigured-kubernetes-horizontal-pod-autoscaler
    - args:
        kubernetesObject:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: image-provider
            namespace: otel-demo
      id: misconfigured-kubernetes-horizontal-pod-autoscaler
  tools:
    finops:
      enabled: true
