apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-46
spec:
  applications:
    opentelemetryDemo:
      enabled: true
  faults:
    - injections:
        - args:
            container:
              name: postgresql
            kubernetesObject:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: postgresql
                namespace: otel-demo
          id: insufficient-kubernetes-workload-container-resources
  tools:
    sre:
      enabled: true
