---
- name: Verify that fault injection succeeded
  hosts:
    - environment
  tasks:
    - name: Retrieve workload
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: apps/v1
        kind: Deployment
        name: compromised-workload
        namespace: insufficient-kubernetes-workload-container-resources-test
      register: faults_deployment

    - name: Validate that container resources were updated
      ansible.builtin.assert:
        that:
          - faults_deployment.resources[0].spec.template.spec.containers[0].resources.limits.cpu == "5m"
          - faults_deployment.resources[0].spec.template.spec.containers[0].resources.limits.memory == "5Mi"
          - faults_deployment.resources[0].spec.template.spec.containers[0].resources.requests.cpu == "5m"
          - faults_deployment.resources[0].spec.template.spec.containers[0].resources.requests.memory == "5Mi"
        fail_msg: Container resources were not updated correctly. Fault injection failed.
        success_msg: Container resources were updated.
