name: Validate SRE docs

on:
  pull_request:
    branches:
      - main
    paths:
      - scenarios/sre/roles/documentation/files/library/**
      - scenarios/sre/roles/documentation/templates/library/**

jobs:
  validate-docs:
    name: Validate documents
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.3.0
        with:
          working-directory: scenarios/sre
      - name: Install project dependencies
        run: |
          make -C scenarios/sre deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group_vars
      - name: Run validation playbook
        run: |
          make -C scenarios/sre validate-docs
