name: Perform AWX smoke tests for SRE incidents

on:
  pull_request:
    branches:
      - main
    paths:
      - scenarios/sre/dev/local_cluster/go.*
      - scenarios/sre/roles/awx/**
      - scenarios/sre/playbooks/manage_awx.yaml

concurrency:
  group: ci-awx-${{ github.ref }}
  cancel-in-progress: true

jobs:
  awx:
    name: AWX Smoke Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.3.0
        with:
          working-directory: scenarios/sre
      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: scenarios/sre/dev/local_cluster/go.mod
          cache-dependency-path: scenarios/sre/dev/local_cluster/go.sum
      - uses: azure/setup-helm@v4.3.1
        with:
          version: v3.19.0
      - name: Create Kind cluster
        run: |
          make -C scenarios/sre/dev/local_cluster create-awx-cluster
      - name: Run Cloud Provider
        run: |
          make -C scenarios/sre/dev/local_cluster run-service-provider &
      - name: Install project dependencies
        run: |
          make -C scenarios/sre deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group-vars
          make -C scenarios/sre -f Makefile.runner group-vars
      - name: Run installation tests
        run: |
          make -C scenarios/sre -f Makefile.runner deploy-awx-stack
      - name: Run configuration tests
        run: |
          make -C scenarios/sre -f Makefile.runner configure-awx-pipeline
      - name: Run uninstallation tests
        run: |
          make -C scenarios/sre -f Makefile.runner undeploy-awx-stack
