name: Validate SRE docs

on:
  pull_request:
    branches:
      - main
    paths:
      - scenarios/sre/roles/documentation/files/library/**
      - scenarios/sre/roles/documentation/templates/library/**

jobs:
  validate-docs:
    name: Validate documents
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.13'
      - name: Install Python and Ansible dependencies
        run: |
          pip install -r scenarios/sre/requirements.txt
          ansible-galaxy install -r scenarios/sre/requirements.yaml
      - name: Create group vars
        run: |
          make -C scenarios/sre group_vars
      - name: Run validation playbook
        run: |
          make -C scenarios/sre validate_docs
