name: Perform AWX smoke tests for SRE incidents

on:
  pull_request:
    branches:
      - main
    paths:
      - scenarios/sre/dev/local_cluster/go.*
      - scenarios/sre/roles/awx/**
      - scenarios/sre/playbooks/manage_awx.yaml

concurrency:
  group: ci-awx-${{ github.ref }}
  cancel-in-progress: true

jobs:
  awx:
    name: AWX Smoke Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.13'
      - uses: actions/setup-go@v6.2.0
        with:
          go-version-file: scenarios/sre/dev/local_cluster/go.mod
          cache-dependency-path: scenarios/sre/dev/local_cluster/go.sum
      - uses: azure/setup-helm@v4.3.1
        with:
          version: v3.19.0
      - name: Install Python and Ansible dependencies
        run: |
          pip install -r scenarios/sre/requirements.txt
          ansible-galaxy install -r scenarios/sre/requirements.yaml
      - name: Create Kind cluster
        run: |
          make -C scenarios/sre/dev/local_cluster create_awx_cluster
      - name: Run Cloud Provider
        run: |
          make -C scenarios/sre/dev/local_cluster run_service_provider &
      - name: Create group vars
        run: |
          make -C scenarios/sre group_vars
          make -C scenarios/sre -f Makefile.runner group_vars
      - name: Run installation tests
        run: |
          make -C scenarios/sre -f Makefile.runner deploy_awx_stack
      - name: Run configuration tests
        run: |
          make -C scenarios/sre -f Makefile.runner configure_awx_pipeline
      - name: Run uninstallation tests
        run: |
          make -C scenarios/sre -f Makefile.runner undeploy_awx_stack
